# Site settings
title: Utkarsh Malik
description: A blog about lorem ipsum dolor sit amet
baseurl: "/" # the subpath of your site, e.g. /blog
url: "utkarshmalik211.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Utkarsh Malik
user_description: Aspiring Data Scientist | CS Undergrad.
user_title: 
email: utkarshmalik211@gmail.com
twitter_username: utkarshmalik211
github_username:  utkarshmalik211
gplus_username:  utkarshmalik211

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
