name: Utkarsh Malik | Blog
description: Blogging 
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /blog
domain_name: 'https://utkarshmalik211.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
